// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZkeah60MfZO-kYmwhXxQYHrcHjYd0rA',
    appId: '1:1094785253067:web:4f401b388baf31aa47654e',
    messagingSenderId: '1094785253067',
    projectId: 'gainer-app',
    authDomain: 'gainer-app.firebaseapp.com',
    storageBucket: 'gainer-app.firebasestorage.app',
    measurementId: 'G-WMDTD1B2BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOGMeh0fnCdadooQJOOFglsL5lJa0Afag',
    appId: '1:1094785253067:android:5392f5c6e64954db47654e',
    messagingSenderId: '1094785253067',
    projectId: 'gainer-app',
    storageBucket: 'gainer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwQTOS0hIbdnr_PYfdYkqwobPit8lUOSA',
    appId: '1:1094785253067:ios:09908a925abeaccb47654e',
    messagingSenderId: '1094785253067',
    projectId: 'gainer-app',
    storageBucket: 'gainer-app.firebasestorage.app',
    iosBundleId: 'com.app.gainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwQTOS0hIbdnr_PYfdYkqwobPit8lUOSA',
    appId: '1:1094785253067:ios:09908a925abeaccb47654e',
    messagingSenderId: '1094785253067',
    projectId: 'gainer-app',
    storageBucket: 'gainer-app.firebasestorage.app',
    iosBundleId: 'com.app.gainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZkeah60MfZO-kYmwhXxQYHrcHjYd0rA',
    appId: '1:1094785253067:web:b766dc17ab2c510147654e',
    messagingSenderId: '1094785253067',
    projectId: 'gainer-app',
    authDomain: 'gainer-app.firebaseapp.com',
    storageBucket: 'gainer-app.firebasestorage.app',
    measurementId: 'G-0VH3QNVN1D',
  );
}
